### PR TITLE
Implement support for NeoForge

### LINKED ISSUE #12: NeoForged support
Currently, this error occurs
```
Exception caught from launcher
java.lang.RuntimeException: Unable to detect the forge installer!
	at io.github.zekerzhayard.forgewrapper.installer.detector.IFileDetector.getDataFromInstaller(IFileDetector.java:136)
	at io.github.zekerzhayard.forgewrapper.installer.detector.IFileDetector.getInstallProfileExtraData(IFileDetector.java:115)
	at io.github.zekerzhayard.forgewrapper.installer.detector.IFileDetector.checkExtraFiles(IFileDetector.java:147)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:29)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
```
Note: https://maven.neoforged.net/#/releases/net/neoforged/forge/

### PR DESCRIPTION
**Pull request by Tkain**
This PR allows for ForgeWrapper to launch NeoForge just as it launches Minecraft Forge. This is mainly accomplished using Forge's `fml.forgeGroup` launch argument, which specifies the base path of Forge-related packages; for Minecraft Forge, this has always been `net.minecraftforge`, whereas NeoForge could use `net.neoforged`. With this PR, ForgeWrapper now stores the value of this flag and uses it when determining the path to the Forge installer.

Additionally, this PR fixes a bug preventing ForgeWrapper from compiling on Java versions newer than Java 8, which I found useful developing using Java 17.

Resolves #12.

### CODE REVIEW

**Comment by Tkain** [comment]
Now that I've come across [concrete proof of it](https://github.com/neoforged/FancyModLoader/commit/b6daf9895b8f09957be5e8df1fbf6b81f37cd0f8), I should also acknowledge that NeoForge's version of FML doesn't actually use the `fml.forgeGroup` flag for anything anymore; only the original Minecraft Forge's FML uses it. I'm open to changing things if this is unsuitable for distinguishing Forge and NeoForge, but it'll probably take extra work.

**Comment by Tkain** [comment]
I'd say the PR is feature-complete now, so I'm un-marking it as a draft. That said, there is still one lingering issue I haven't been able to figure out during development, but I'm not sure if it's related to the PR or not; when launching an installed NeoForge instance, NeoForge crashes because it can't find its built-in language providers. From what I've investigated regarding the issue, for whatever reason the language provider classes don't end up in FancyModLoader's class loader despite being on the classpath. Classic Forge works as expected, however.

I'll update the PR with a fix if I can find one out, but I've had no luck over the last two days.

**Edit:** This (hopefully) might be just a NeoForge bug; see https://github.com/neoforged/NeoForge/pull/68.

**Comment by ZekerZhayard** [comment]
In response to your crashes, I'll look into it this weekend and discuss it when I have a definitive solution.

**Comment by Tkain** [comment]
No need! As of NeoForge version 47.1.60 (where the bug I mentioned was fixed), NeoForge works as expected when installed using this PR!

**Comment by Pyker** [comment]
Can a release be created to push out these changes?

**Comment by ZekerZhayard** [comment]
@Pyker released

**Comment by Pyker** [comment]
Thanks!

**Comment by Pyker** [comment]
I confirm, it works just fine!

**Pull request merged**
